services:
  translate-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        UVICORN_WORKERS: 1
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - ../models:/app/models
    env_file:
      - ../.env
    environment:
      - UVICORN_WORKERS=1
