services:
  translate-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ../models:/app/models
    env_file:
      - ../.env
